---
title: "QuantedaUI Manual"
author: "Ogulcan Gok"
date: "March 6, 2018"
output:
  html_document: default
  pdf_document: default
---



## General Information



Welcome to QuantedaUI. Created by Ahmet Süerdem, Fuat Can Beylunioğlu and Oğulcan Gök. This application will help you to analyze your text data by creating various plots. IN order to use you should arrange your data in a CSV file. Your text column name should be "Text" and date format must be DD/MM/YYYY. 

You can initilaze the app by uploading your CSV to the slot located in Corpus Creation tab. After the calculations the app will create a .rda file to your working
directory which you can upload to continue to your work anytime you want. It will hold all the changes you make to your csv file. 

If you want to save your progress any moment, you can just simply click the save button.

Let's see the basics..

## 1)Corpus Creation 

In this tab your can upload your csv to create corpus from it. The app will calculate the readability with your desired factor and add it to csv as a column. See the sample code below.


## 2)Data 

In this tab, you can display each text by clicking the corresponding text line in the dataframe. A pop up window with the text will open. Also you can add notes to your corpus in this tab.

## 3)Explore 

### 3.a)Box Plots

In this tab you can plot a box plot with the desired parameters. As an example you can plot BoxPlot for number of tokens by year.



### 3.b)Corresponce Plot 

#### -Lexical

 This page has one select input and two text inputs. These will allow you to print a lexical dispersion plot of a choosen year with two given key words. You can also print for only one key word just by filling only the first text box.
 

 

#### -Text

This tab will allow you to create subsets and saving them. Also you can enter a key word to see them in context. It will rende rout a table which displays six words after and before of your keyword.



## 4)DFM 

### 4.a)Plots

This tab will let you plot Text Cloud or Frequency plot with given input value.



### 4.b)Grouping

You will see two select inputs. One will contain the headers from your corpus other will contain plot types. This tab will group your corpuses with the given grouping filter and it will render the choosen plot type.



### 4.c)Frequency
In Frequency tab you can enter your own keyword to see it's frequency throughout the years. If you increase the slider input, you will see the most frequent
words throughout the years. Slider input will change the number of the words in plots.

Filter the term "musk"


### 4.d)Keyness

This page will have two select inputs which contains the years of the corpuses. You can select two year values to compare them with a keyness plot.



### 4.e)Dictionary

You can upload your own dictionary to compare the corpuses with the dictionary's categories.



### 4.f)Similarity

You can choose a year to calculate similarity with the given parameter.





